server:
  port: 80
  servlet:
    context-path: /crm
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_crm?serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML
mybatis-plus:
  mapper-locations: classpath*:me/hibiki/crm/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: me.hibiki.crm.domain
logging:
  level:
    me.hibiki.crm: trace
